#!/usr/bin/env bash

printf "Starting Internet Router build. Please allow up to 20 minutes.\n"
./tools/cleanup_failed_session  > /dev/null 2>&1

export ANSIBLE_HOST_KEY_CHECKING=False
cd ./provisioning/packer/

packer build -force internetrouter.json

if [ $? != 0 ]; then
	printf "Packer exited with non-zero return code.\nResetting all previously built machines to their old snapshots...\n"
	../../tools/cleanup_failed_session  > /dev/null 2>&1
	exit 1
fi

cd ../..
./tools/cleanup_failed_session  > /dev/null 2>&1
printf "Task finished.\n\n"
