#!/usr/bin/env bash

printf "Starting build. Please allow up to 120 minutes.\n"
./tools/cleanup_failed_session  > /dev/null 2>&1

vboxmanage startvm "Internet Router" --type headless
vboxmanage startvm "Company Router" --type headless
vboxmanage startvm "Log Server" --type headless
export ANSIBLE_HOST_KEY_CHECKING=False
cd ./provisioning/packer/

packer build -force client.json

if [ $? != 0 ]; then
	printf "Packer exited with non-zero return code.\nResetting all previously built machines to their old snapshots...\n"
	../../tools/cleanup_failed_session  > /dev/null 2>&1
	exit 1
fi

vboxmanage controlvm "Log Server" acpipowerbutton
echo "Waiting until Log Server shuts down completely before taking snapshot..."

for i in {1..300}; do
  sleep 1
  if ! vboxmanage list runningvms | grep -q "Log Server"; then
    break
  fi
done
sleep 5

vboxmanage snapshot "Log Server" edit "fresh" --name "pre_client_build"
vboxmanage snapshot "Log Server" take "fresh"

cd ../..
./tools/cleanup_failed_session  > /dev/null 2>&1
printf "Task finished.\n\n"
