#!/usr/bin/env bash

printf "Starting Attacker build. Please allow up to 40 minutes.\n"
./tools/cleanup_failed_session  > /dev/null 2>&1

vboxmanage startvm "Internet Router" --type headless
export ANSIBLE_HOST_KEY_CHECKING=False
cd ./provisioning/packer/

packer build -force attacker.json

if [ $? != 0 ]; then
	printf "Packer exited with non-zero return code.\nResetting all previously built machines to their old snapshots...\n"
	../../tools/cleanup_failed_session  > /dev/null 2>&1
	exit 1
fi

cd ../..
./tools/cleanup_failed_session  > /dev/null 2>&1
printf "Task finished.\n\n"
