name: SOCBED System Tests

on:
  schedule:
    - cron: "0 1 * * MON-FRI" # At 01:00 on every day-of-week from Monday through Friday
  workflow_dispatch:
  
jobs:
  build-machines:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v2
      
      - name: Define iso cache
        uses: MasterworksIO/action-local-cache@main
        with:
          path: "./provisioning/packer/packer_cache/"
          key: "iso_cache"
          
      - name: Define exports cache
        uses: MasterworksIO/action-local-cache@main
        with:
          path: "./provisioning/packer/exports/"
          key: "exports_cache"
          
      - name: Define builds cache
        uses: MasterworksIO/action-local-cache@main
        with:
          path: "./provisioning/packer/packer_builds/"
          key: "builds_cache"
      
      - name: Build Internet Router
        run: ./tools/build_internetrouter
      
      - name: Build Company Router
        run: ./tools/build_companyrouter
   
  delete-machines:
    runs-on: [self-hosted, linux]
    if: always()
    needs: [build-machines]
    steps:
      - uses: actions/checkout@v2
      
      - name: Define iso cache
        uses: MasterworksIO/action-local-cache@main
        with:
          path: "./provisioning/packer/packer_cache/"
          key: "iso_cache"
          
      - name: Define iso cache
        uses: MasterworksIO/action-local-cache@main
        with:
          path: "./provisioning/packer/exports/"
          key: "exports_cache"
          
      - name: Define iso cache
        uses: MasterworksIO/action-local-cache@main
        with:
          path: "./provisioning/packer/packer_builds/"
          key: "builds_cache"
      
      - name: Delete created VMs
        run: ./tools/delete_vms

