name: SOCBED System Tests

on:
#  schedule:
#    - cron: "0 1 * * MON-FRI" # At 01:00 on every day-of-week from Monday through Friday
  workflow_dispatch:
  
jobs:
  build-machines:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v2
      - name: Build Internet Router
        run: ./tools/build_internetrouter

