name: SOCBED System Tests

on:
  schedule:
    - cron: "0 1 * * MON-FRI" # At 01:00 on every day-of-week from Monday through Friday
  workflow_dispatch:
  
jobs:
  build-machines:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v2
      
      - name: Build Internet Router
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 60
          max_attempts: 3
          command: ./tools/build_internetrouter runner
      
      - name: Build Company Router
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 60
          max_attempts: 3
          command: ./tools/build_companyrouter runner
        
      - name: Build Attacker
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 120
          max_attempts: 3
          command: ./tools/build_attacker runner
        
      - name: Build Log Server
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 60
          max_attempts: 3
          command: ./tools/build_logserver runner
        
      - name: Build Internal Server
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 60
          max_attempts: 3
          command: ./tools/build_internalserver runner
        
      - name: Build DMZ Server
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 60
          max_attempts: 3
          command: ./tools/build_dmzserver runner
        
      - name: Build Client
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 120
          max_attempts: 3
          command: ./tools/build_client runner
        
      - name: Run logging setup
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 60
          max_attempts: 3
          command: ./tools/logging_setup
        
  test-machines:
    runs-on: [self-hosted, linux]
    needs: [build-machines]
    steps:
      - uses: actions/checkout@v2
      
      - name: Ensure all machines are powered off
        run: ./tools/cleanup_failed_session
      
      - name: Run system tests ("not longtest")
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 30
          max_attempts: 3
          command: tox -- -m "systest and not longtest"
   
  delete-machines:
    runs-on: [self-hosted, linux]
    if: always()
    needs: [build-machines, test-machines]
    steps:
      - uses: actions/checkout@v2
      
      - name: Delete created VMs
        run: ./tools/delete_vms

