name: SOCBED System Tests

on:
  schedule:
    - cron: "0 1 * * MON-FRI" # At 01:00 on every day-of-week from Monday through Friday
  workflow_dispatch:
  
jobs:
  build-machines:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up iso cache
        uses: MasterworksIO/action-local-cache@main
        with:
          path: "./provisioning/packer/packer_cache/"
          key: "iso_cache"
      
      - name: Build Internet Router
        run: ./tools/build_internetrouter
      
      - name: Build Company Router
        run: ./tools/build_companyrouter
        
      - name: Build Attacker
        run: ./tools/build_attacker
        
      - name: Build Log Server
        run: ./tools/build_logserver
        
      - name: Build Internal Server
        run: ./tools/build_internalserver
        
      - name: Build DMZ Server
        run: ./tools/build_dmzserver
        
      - name: Build Client
        run: ./tools/build_client
        
      - name: Run loggins setup
        run: ./tools/logging_setup
        
  test-machines:
    runs-on: [self-hosted, linux]
    needs: [build-machines]
    steps:
      - uses: actions/checkout@v2
      
      - name: Ensure all machines are powered off
        run: ./tools/cleanup_failed_session
      
      - name: Run system tests ("not longtest")
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 30
          max_attempts: 3
          command: tox -- -m "systest and not longtest"
   
  delete-machines:
    runs-on: [self-hosted, linux]
    if: always()
    needs: [build-machines, test-machines]
    steps:
      - uses: actions/checkout@v2
      
      - name: Delete created VMs
        run: ./tools/delete_vms

